"""
Configuration module for the DISTIL R10 Object Detection project.
"""

from .config import (
    DEVICE,
    DEFAULT_ARCHITECTURE,
    DEFAULT_ROOT_DIR,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_OUTPUT_FILE,
    DEFAULT_IMAGE_SIZE,
    DEFAULT_NUM_CLASSES,
    TRIGGER_CONFIDENCE_THRESHOLD,
    DEFAULT_GUIDANCE_SCALE,
    DEFAULT_TIMESTEPS,
    DEFAULT_BATCH_SIZE,
    USE_WARNINGS
) 